import type { CSSProperties, ReactNode } from "react";
import { formatPrice } from "../../../lib/utils";
import { AdminEmptyState, AdminQuickActions, AdminStatCard, AdminStatsGrid, AdminSurface } from "../AdminUI";

type Order = { id: number; totalPrice?: number | string | null; customerName?: string | null; customerEmail?: string | null; userId?: number | null; createdAt?: Date | string | null; fulfillmentStatus?: string | null; payment?: { status?: string | null } | null };
type Product = { id: number; name?: string | null; category?: string | null; stock?: number | string | null };
type Audit = { id: number; action: string; entity: string; entityId?: string | null; createdAt: Date | string };
type Kpis = { salesToday?: number | null; pendingOrders?: number | null; ordersToday?: number | null; usersCount?: number | null; productsCount?: number | null; lowStockCount?: number | null };
type Props = { dashboardData?: Kpis | null; isMobile: boolean; isCompact: boolean; orders: Order[]; products: Product[]; promoBanners: Array<{ isActive?: boolean | number | null }>; coupons: Array<{ isActive?: boolean | number | null }>; recentAudit: Audit[]; quickActions: Array<{ label: string; caption: string; onClick: () => void }>; ordersLoading: boolean; productsLoading: boolean; inventoryExceptions: number; onViewOrder: (id: number) => void; onViewProduct: (product: Product) => void; children?: ReactNode };

const paidStatuses = new Set(["confirmed", "received", "partially_refunded"]);
const fulfillmentRows = [["awaiting_payment", "Aguardando pagamento"], ["ready", "Pronto para separação"], ["processing", "Em separação"], ["shipped", "Enviado"], ["delivered", "Entregue"], ["cancelled", "Cancelado"]] as const;
const money = (value: number | string | null | undefined) => Number(value ?? 0) / 100;
const canonicalPaymentState = (order: Order) => String(order.payment?.status ?? "pending");
const active = (value: boolean | number | null | undefined) => value === true || value === 1;
function Icon({ children }: { children: ReactNode }) { return <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{children}</svg>; }
function Badge({ children, style }: { children: ReactNode; style: CSSProperties }) { return <span style={{ ...styles.badge, ...style }}>{children}</span>; }
function fulfillmentTone(status: string): CSSProperties { if (status === "delivered") return { background: "rgba(126,34,206,.14)", border: "1px solid rgba(126,34,206,.28)", color: "#d8b4fe" }; if (status === "shipped") return { background: "rgba(37,99,235,.14)", border: "1px solid rgba(37,99,235,.28)", color: "#93c5fd" }; if (["processing", "ready"].includes(status)) return { background: "rgba(15,118,110,.14)", border: "1px solid rgba(15,118,110,.28)", color: "#5eead4" }; if (status === "cancelled") return { background: "rgba(185,28,28,.14)", border: "1px solid rgba(185,28,28,.28)", color: "#fca5a5" }; return { background: "rgba(180,83,9,.14)", border: "1px solid rgba(180,83,9,.28)", color: "#fbbf24" }; }

export function AdminDashboard({ dashboardData, isMobile, isCompact, orders, products, promoBanners, coupons, recentAudit, quickActions, ordersLoading, productsLoading, inventoryExceptions, onViewOrder, onViewProduct }: Props) {
  const paidOrders = orders.filter(order => paidStatuses.has(canonicalPaymentState(order)));
  const loadedRevenue = paidOrders.reduce((total, order) => total + money(order.totalPrice), 0);
  const lowStock = products.filter(product => Number(product.stock ?? 0) <= 5).slice(0, 6);
  const alerts = [
    ...(inventoryExceptions ? [{ title: `${inventoryExceptions} exceção(ões) de estoque`, description: "Há pedidos que exigem revisão operacional antes do envio.", danger: true }] : []),
    ...(lowStock.length ? [{ title: `${lowStock.length} produto(s) com estoque baixo`, description: "Revise a reposição dos itens destacados no catálogo.", danger: false }] : []),
  ];
  return <section aria-label="Visão geral administrativa" style={styles.stack}>
    <AdminStatsGrid style={{ gridTemplateColumns: isMobile ? "1fr" : isCompact ? "repeat(2, minmax(0, 1fr))" : "repeat(3, minmax(0, 1fr))" }}>
      <AdminStatCard label="Vendas de hoje" value={formatPrice((dashboardData?.salesToday ?? 0) / 100)} hint="Considera pedidos entregues no dia." tone="success" icon={<Icon><path d="M12 20V10" /><path d="m18 20-6-6-6 6" /></Icon>} />
      <AdminStatCard label="Pedidos pendentes" value={String(dashboardData?.pendingOrders ?? 0)} hint="Pedidos aguardando pagamento." tone="warning" icon={<Icon><circle cx="12" cy="12" r="8" /><path d="M12 8v5l3 2" /></Icon>} />
      <AdminStatCard label="Pedidos hoje" value={String(dashboardData?.ordersToday ?? 0)} hint="Criados desde 00:00." tone="info" icon={<Icon><rect x="3" y="6" width="18" height="15" rx="2" /></Icon>} />
      <AdminStatCard label="Clientes" value={String(dashboardData?.usersCount ?? 0)} hint="Usuários com conta no sistema." icon={<Icon><circle cx="9" cy="7" r="4" /><path d="M2 21v-2a4 4 0 0 1 4-4h6a4 4 0 0 1 4 4v2" /></Icon>} />
      <AdminStatCard label="Produtos ativos" value={String(dashboardData?.productsCount ?? 0)} hint="Itens disponíveis no catálogo." icon={<Icon><path d="M3 9h18v12H3z" /><path d="M6 9V5h12v4" /></Icon>} />
      <AdminStatCard label="Estoque baixo" value={String(dashboardData?.lowStockCount ?? 0)} hint="Produtos com 5 unidades ou menos." tone="warning" icon={<Icon><path d="M12 3 2 21h20L12 3z" /><path d="M12 9v4" /></Icon>} />
    </AdminStatsGrid>
    <AdminSurface title="Visão financeira e operação" description="Indicadores calculados somente com os pedidos carregados no painel."><div style={styles.metricGrid}>
      <Metric label="Faturamento carregado" value={formatPrice(loadedRevenue)} /><Metric label="Ticket médio" value={formatPrice(paidOrders.length ? loadedRevenue / paidOrders.length : 0)} /><Metric label="Pedidos pagos" value={String(paidOrders.length)} /><Metric label="Pedidos enviados" value={String(orders.filter(order => order.fulfillmentStatus === "shipped").length)} /><Metric label="Cancelados" value={String(orders.filter(order => order.fulfillmentStatus === "cancelled").length)} danger /><Metric label="Banners ativos" value={`${promoBanners.filter(row => active(row.isActive)).length}/${promoBanners.length}`} /><Metric label="Cupons ativos" value={`${coupons.filter(row => active(row.isActive)).length}/${coupons.length}`} /><Metric label="Produtos cadastrados" value={String(products.length)} />
    </div></AdminSurface>
    <div style={{ ...styles.columns, gridTemplateColumns: isCompact ? "1fr" : styles.columns.gridTemplateColumns }}><AdminSurface title="Ações rápidas" description="Atalhos para as rotinas mais frequentes do painel."><AdminQuickActions actions={quickActions} /></AdminSurface><AdminSurface title="Status do sistema" description="Resumo baseado nos dados disponíveis no painel."><div style={styles.statusList}><Status label="Pedidos em aberto" value={String(dashboardData?.pendingOrders ?? 0)} /><Status label="Catálogo publicado" value={`${dashboardData?.productsCount ?? 0} itens`} /><Status label="Cadastros ativos" value={`${dashboardData?.usersCount ?? 0} usuários`} /></div></AdminSurface></div>
    <div style={{ ...styles.columns, gridTemplateColumns: isCompact ? "1fr" : styles.columns.gridTemplateColumns }}><AdminSurface title="Pedidos por status" description="Distribuição logística por fulfillmentStatus."><div style={styles.statusGrid}>{fulfillmentRows.map(([status, label]) => <div key={status} style={styles.statusCard}><Badge style={fulfillmentTone(status)}>{label}</Badge><strong style={styles.value}>{orders.filter(order => order.fulfillmentStatus === status).length}</strong></div>)}</div></AdminSurface><AdminSurface title="Alertas operacionais" description="Sinais rápidos para priorizar a rotina da loja.">{alerts.length ? <div style={styles.alertList}>{alerts.map(alert => <div key={alert.title} style={{ ...styles.alert, ...(alert.danger ? styles.alertDanger : styles.alertWarning) }}><strong>{alert.title}</strong><span>{alert.description}</span></div>)}</div> : <AdminEmptyState title="Sem alertas agora" description="Nenhum dado carregado exige atenção imediata." />}</AdminSurface></div>
    <div style={{ ...styles.columns, gridTemplateColumns: isCompact ? "1fr" : styles.columns.gridTemplateColumns }}><AdminSurface title="Últimos pedidos" description="Pagamento e logística são exibidos separadamente.">{ordersLoading ? <div style={styles.loading}>Carregando pedidos...</div> : orders.length === 0 ? <AdminEmptyState title="Sem pedidos carregados" description="Quando houver pedidos, os mais recentes aparecerão aqui." /> : <div style={styles.list}>{orders.slice(0, 6).map(order => <button key={order.id} type="button" style={styles.listButton} onClick={() => onViewOrder(order.id)}><span><strong>Pedido #{order.id}</strong><small>{order.customerName || order.customerEmail || `Cliente #${order.userId}`}</small></span><span style={styles.right}><strong>{formatPrice(money(order.totalPrice))}</strong><Badge style={fulfillmentTone(String(order.fulfillmentStatus ?? "awaiting_payment"))}>{String(order.fulfillmentStatus ?? "awaiting_payment")}</Badge><small>Pagamento: {canonicalPaymentState(order)}</small></span></button>)}</div>}</AdminSurface><AdminSurface title="Produtos com baixo estoque" description="Itens com 5 unidades ou menos para priorizar revisão.">{productsLoading ? <div style={styles.loading}>Carregando produtos...</div> : lowStock.length === 0 ? <AdminEmptyState title="Estoque saudável" description="Nenhum produto carregado está com estoque baixo." /> : <div style={styles.list}>{lowStock.map(product => <button key={product.id} type="button" style={styles.listButton} onClick={() => onViewProduct(product)}><span><strong>{product.name || `Produto #${product.id}`}</strong><small>{product.category || "Sem categoria"}</small></span><strong style={Number(product.stock ?? 0) <= 0 ? styles.out : styles.low}>{Number(product.stock ?? 0) <= 0 ? "Sem estoque" : `${product.stock} un.`}</strong></button>)}</div>}</AdminSurface></div>
    <AdminSurface title="Atividade recente" description="Últimos eventos registrados na trilha de auditoria administrativa.">{recentAudit.length === 0 ? <AdminEmptyState title="Sem atividade recente" description="Assim que o painel registrar ações administrativas, elas aparecerão aqui." /> : <div style={styles.activity}>{recentAudit.map(item => <div key={item.id} style={styles.activityItem}><i style={styles.dot} /><span><strong>{item.action}</strong><small>{item.entity} {item.entityId ? `#${item.entityId}` : ""} · {new Date(item.createdAt).toLocaleString("pt-BR")}</small></span></div>)}</div>}</AdminSurface>
  </section>;
}
function Metric({ label, value, danger = false }: { label: string; value: string; danger?: boolean }) { return <div style={{ ...styles.metric, ...(danger ? styles.metricDanger : {}) }}><span>{label}</span><strong>{value}</strong></div>; }
function Status({ label, value }: { label: string; value: string }) { return <div style={styles.status}><span>{label}</span><strong>{value}</strong></div>; }
const styles: Record<string, CSSProperties> = { stack: { display: "grid", gap: 20 }, columns: { display: "grid", gridTemplateColumns: "minmax(0, 1.4fr) minmax(280px, .8fr)", gap: 20 }, metricGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))", gap: 12 }, metric: { display: "grid", gap: 10, minHeight: 104, padding: "15px 16px", borderRadius: 13, border: "1px solid rgba(255,255,255,.07)", background: "#090909", color: "#f8f4ec" }, metricDanger: { borderColor: "rgba(239,68,68,.24)" }, statusList: { display: "grid", gap: 9 }, status: { display: "flex", justifyContent: "space-between", padding: "12px 14px", borderRadius: 11, background: "#090909", border: "1px solid rgba(255,255,255,.065)", color: "#f8f4ec" }, statusGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(142px, 1fr))", gap: 10 }, statusCard: { display: "grid", gap: 10, padding: 13, borderRadius: 12, border: "1px solid rgba(255,255,255,.065)", background: "#090909" }, badge: { display: "inline-flex", width: "fit-content", padding: "6px 9px", borderRadius: 999, fontSize: 12, fontWeight: 700 }, value: { color: "#f8f4ec", fontSize: 25 }, alertList: { display: "grid", gap: 10 }, alert: { display: "grid", gap: 5, padding: 14, borderRadius: 11, color: "#d1d5db" }, alertDanger: { border: "1px solid rgba(239,68,68,.32)", background: "rgba(127,29,29,.16)" }, alertWarning: { border: "1px solid rgba(245,158,11,.32)", background: "rgba(120,53,15,.16)" }, list: { display: "grid", gap: 8 }, listButton: { display: "flex", justifyContent: "space-between", gap: 12, textAlign: "left", padding: "12px 14px", borderRadius: 11, border: "1px solid rgba(255,255,255,.065)", background: "#090909", color: "#f8f4ec", cursor: "pointer" }, right: { display: "grid", justifyItems: "end", gap: 4 }, low: { color: "#fcd34d" }, out: { color: "#fca5a5" }, loading: { color: "#9ca3af", padding: 12 }, activity: { display: "grid", gap: 10 }, activityItem: { display: "flex", gap: 10, padding: "10px 0", color: "#f8f4ec" }, dot: { width: 8, height: 8, borderRadius: 999, background: "#e8002a", marginTop: 6, flexShrink: 0 } };
