import { useState } from "react";
import type { CSSProperties } from "react";
import { trpc } from "../../lib/trpc";
import { useToast } from "../../contexts/ToastContext";
import { AdminSystemUI } from "../../components/admin/system/AdminSystemUI";
import { AdminEmptyState, AdminSurface } from "../../components/admin/AdminUI";

export function BackupPage() {
  const { showToast } = useToast(); const [fileName, setFileName] = useState("");
  const query = trpc.admin.backupsList.useQuery(); const utils = trpc.useUtils();
  const manual = trpc.admin.backupManual.useMutation({ onSuccess: data => { showToast({ message: `Backup criado: ${data.fileName}`, duration: 2600 }); void query.refetch(); }, onError: error => showToast({ message: error.message, duration: 2600 }) });
  const restore = trpc.admin.backupRestore.useMutation({ onSuccess: () => { showToast({ message: "Backup restaurado", duration: 2600 }); void Promise.all([utils.admin.usersList.invalidate(), utils.admin.productsList.invalidate(), utils.admin.ordersList.invalidate(), utils.admin.couponsList.invalidate(), utils.admin.auditList.invalidate()]); }, onError: error => showToast({ message: error.message, duration: 2600 }) });
  return <AdminSystemUI><AdminSurface title="Backup" description="Crie backups manuais e restaure arquivos conhecidos com confirmação explícita."><div style={styles.row}><button style={styles.primary} disabled={manual.isPending} onClick={() => manual.mutate()}>{manual.isPending ? "Criando..." : "Backup manual"}</button><input style={styles.input} placeholder="arquivo-backup.json" value={fileName} onChange={event => setFileName(event.target.value)} /><button style={styles.button} disabled={restore.isPending} onClick={() => { if (!fileName.trim()) { showToast({ message: "Informe o nome do arquivo de backup", duration: 2300 }); return; } if (!window.confirm("Restaurar backup substitui dados atuais. Continuar?")) return; restore.mutate({ fileName: fileName.trim(), confirmation: "RESTORE" }); }}>{restore.isPending ? "Restaurando..." : "Restaurar"}</button></div>{query.isLoading ? <div style={styles.loading}>Carregando backups...</div> : !(query.data ?? []).length ? <AdminEmptyState title="Nenhum backup disponível" description="Crie um backup manual para que ele apareça listado aqui." /> : <div style={styles.tableWrap}><table style={styles.table}><thead><tr><th>Arquivos disponíveis</th></tr></thead><tbody>{(query.data ?? []).map(file => <tr key={file}><td>{file}</td></tr>)}</tbody></table></div>}</AdminSurface></AdminSystemUI>;
}
const styles: Record<string, CSSProperties> = { row: { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }, input: { border: "1px solid #27272a", background: "#111111", color: "#f0ede8", borderRadius: 12, padding: "12px 14px", minHeight: 46 }, primary: { border: "1px solid #3a3a3a", background: "linear-gradient(135deg, #1a1a1a 0%, #3a3a3a 100%)", color: "#fff", borderRadius: 8, padding: "12px 16px", cursor: "pointer", minWidth: 180, fontWeight: 800 }, button: { border: "1px solid #2f2f2f", background: "#111111", color: "#f0ede8", borderRadius: 8, padding: "10px 14px", cursor: "pointer", fontWeight: 700 }, loading: { padding: "28px 18px", color: "#9ca3af", textAlign: "center" }, tableWrap: { overflowX: "auto", border: "1px solid #2f2f2f", borderRadius: 10 }, table: { width: "100%", borderCollapse: "separate", borderSpacing: 0, fontSize: 14, color: "#e5e7eb", textAlign: "center" } };
