import mysql, { type Connection } from "mysql2/promise";
import sharp from "sharp";
import { unlink } from "node:fs/promises";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

const url = process.env.TEST_DATABASE_URL || "";
const origin = "http://test.l4ckos.local";
let connection: Connection;
let baseUrl = "";
let closeServer: (() => Promise<void>) | undefined;
let sessionCookie = "";
let csrfCookie = "";
let csrfHeader = "";
async function clean() { for (const table of ["productReviewUploads", "productReviews", "payments", "stockReservations", "orderItems", "orders", "products", "users"]) await connection.query(`DELETE FROM \`${table}\``); }
async function upload(init: { cookie?: string; token?: string; form?: FormData; origin?: string } = {}) { return fetch(`${baseUrl}/api/review-images`, { method: "POST", headers: { Origin: init.origin ?? origin, ...(init.cookie ? { Cookie: init.cookie } : {}), ...(init.token ? { "x-csrf-token": init.token } : {}) }, body: init.form ?? new FormData() }); }
async function eligible() { const [u]: any = await connection.query("INSERT INTO users(openId,role,sessionVersion)VALUES('review-http-test-user','user',1)"); const [p]: any = await connection.query("INSERT INTO products(name,category,price,stock)VALUES('p','c',1,1)"); const [o]: any = await connection.query("INSERT INTO orders(userId,status,totalPrice,fulfillmentStatus)VALUES(?,'delivered',1,'delivered')", [u.insertId]); const [i]: any = await connection.query("INSERT INTO orderItems(orderId,productId,quantity,unitPrice)VALUES(?,?,1,1)", [o.insertId,p.insertId]); await connection.query("INSERT INTO stockReservations(orderId,userId,productId,orderItemId,quantity,status,expiresAt)VALUES(?,?,?,?,1,'consumed',DATE_ADD(NOW(),INTERVAL 1 DAY))", [o.insertId,u.insertId,p.insertId,i.insertId]); await connection.query("INSERT INTO payments(orderId,billingType,amount,externalReference,status,confirmedAt)VALUES(?,'PIX',1,'review-http', 'confirmed',NOW())", [o.insertId]); return { user: u.insertId, product: p.insertId }; }
async function image(productId: number) { const form = new FormData(); form.set("productId", String(productId)); const png = await sharp({ create: { width: 2, height: 2, channels: 3, background: "red" } }).png().toBuffer(); form.set("file", new Blob([png], { type: "image/png" }), "image.png"); return form; }

describe.runIf(/(localhost|127\.0\.0\.1)/.test(url) && /test/i.test(url))("review upload HTTP", () => {
  beforeAll(async () => {
    Object.assign(process.env, { NODE_ENV: "test", APP_ENV: "test", DATABASE_URL: url, JWT_SECRET: "review-http-test-secret-at-least-32-bytes", SESSION_COOKIE_NAME: "l4ckos_test_session", COOKIE_SECURE: "false", COOKIE_SAME_SITE: "lax", FRONTEND_URL: origin, CORS_ORIGINS: origin, MAINTENANCE_MODE: "false", STORAGE_MODE: "disabled", REVIEW_IMAGE_RATE_LIMIT_MAX: "50" });
    connection = await mysql.createConnection(url); const [db]: any = await connection.query("SELECT DATABASE() name"); if (!/test/i.test(db[0].name)) throw Error("test database required");
    const [{ createApp }, { sdk }, { createCsrfToken, CSRF_COOKIE_NAME, CSRF_HEADER_NAME }, { getSessionCookieName }] = await Promise.all([import("./_core/index"), import("./_core/sdk"), import("./_core/csrf"), import("./_core/cookies")]);
    const { app, server } = await createApp(); await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve)); const address = server.address() as import("node:net").AddressInfo; baseUrl = `http://127.0.0.1:${address.port}`; closeServer = () => new Promise(resolve => server.close(() => resolve()));
    const jwt = await sdk.createSessionToken("review-http-test-user", { sessionVersion: 1 }); const csrf = createCsrfToken(); sessionCookie = `${getSessionCookieName()}=${jwt}`; csrfCookie = `${CSRF_COOKIE_NAME}=${csrf}`; csrfHeader = csrf;
  });
  beforeEach(clean);
  afterAll(async () => { await closeServer?.(); await connection?.end(); });
  it("smoke: authenticated CSRF request reaches storage-disabled gate without a token row", async () => { const s = await eligible(); const response = await upload({ cookie: `${sessionCookie}; ${csrfCookie}`, token: csrfHeader, form: await image(s.product) }); expect(response.status).toBe(503); expect(await response.json()).toMatchObject({ code: "STORAGE_DISABLED" }); const [rows]: any = await connection.query("SELECT COUNT(*) total FROM productReviewUploads"); expect(rows[0].total).toBe(0); });
  it("rejects missing auth, missing CSRF, invalid CSRF and forbidden origin before upload", async () => { const s = await eligible(); expect((await upload({ form: await image(s.product) })).status).toBe(401); expect((await upload({ cookie: sessionCookie, form: await image(s.product) })).status).toBe(403); expect((await upload({ cookie: `${sessionCookie}; ${csrfCookie}`, token: "invalid", form: await image(s.product) })).status).toBe(403); expect((await upload({ cookie: `${sessionCookie}; ${csrfCookie}`, token: csrfHeader, origin: "https://evil.invalid", form: await image(s.product) })).status).toBe(403); });
  it("blocks maintenance before creating a token", async () => { const s = await eligible(); process.env.MAINTENANCE_MODE = "true"; const response = await upload({ cookie: `${sessionCookie}; ${csrfCookie}`, token: csrfHeader, form: await image(s.product) }); process.env.MAINTENANCE_MODE = "false"; expect(response.status).toBe(503); const [rows]: any = await connection.query("SELECT COUNT(*) total FROM productReviewUploads"); expect(rows[0].total).toBe(0); });
  it("fails closed for unauthorized local storage and remote storage errors", async () => { const s = await eligible(); process.env.STORAGE_MODE = "local"; const local = await upload({ cookie: `${sessionCookie}; ${csrfCookie}`, token: csrfHeader, form: await image(s.product) }); process.env.STORAGE_MODE = "remote"; const remote = await upload({ cookie: `${sessionCookie}; ${csrfCookie}`, token: csrfHeader, form: await image(s.product) }); process.env.STORAGE_MODE = "disabled"; expect(local.status).toBe(503); expect(remote.status).toBe(503); expect((await remote.json()).code).toBe("STORAGE_UNAVAILABLE"); const [rows]: any = await connection.query("SELECT COUNT(*) total FROM productReviewUploads"); expect(rows[0].total).toBe(0); });
  it("allows explicitly authorized local staging storage and removes the generated WebP", async () => { const s = await eligible(); Object.assign(process.env, { APP_ENV: "staging", STORAGE_MODE: "local", ALLOW_EPHEMERAL_STAGING_STORAGE: "true" }); const response = await upload({ cookie: `${sessionCookie}; ${csrfCookie}`, token: csrfHeader, form: await image(s.product) }); Object.assign(process.env, { APP_ENV: "test", STORAGE_MODE: "disabled", ALLOW_EPHEMERAL_STAGING_STORAGE: "" }); expect(response.status).toBe(201); const body: any = await response.json(); expect(body.previewUrl).toMatch(/\.webp$/); const bytes = Buffer.from(await (await fetch(body.previewUrl)).arrayBuffer()); expect((await sharp(bytes).metadata()).format).toBe("webp"); await unlink(new URL(body.previewUrl).pathname.replace(/^\//, process.cwd() + "/")); const [rows]: any = await connection.query("SELECT COUNT(*) total FROM productReviewUploads"); expect(rows[0].total).toBe(1); });
});
