import mysql, { type Connection } from "mysql2/promise";
import { randomBytes } from "node:crypto";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";

const url = process.env.TEST_DATABASE_URL || "";
let connection: Connection;
async function clean() { for (const table of ["productReviewUploads", "productReviews", "payments", "stockReservations", "orderItems", "orders", "products", "users"]) await connection.query(`DELETE FROM \`${table}\``); }
function caller(id: number) { const now = new Date(); return appRouter.createCaller({ user: { id, openId: `upload-${id}`, name: "Upload", email: "upload@test", cpf: null, phone: null, asaasCustomerId: null, loginMethod: "local", role: "user", isVip: 0, isBlocked: 0, sessionVersion: 1, createdAt: now, updatedAt: now, lastSignedIn: now }, req: {} as TrpcContext["req"], res: {} as TrpcContext["res"] }); }
async function purchase(userId?: number, productId?: number) { let user = userId, product = productId; if (!user) { const [x]: any = await connection.query("INSERT INTO users(openId)VALUES(?)", [crypto.randomUUID()]); user = x.insertId; } if (!product) { const [x]: any = await connection.query("INSERT INTO products(name,category,price,stock)VALUES('p','c',1,3)"); product = x.insertId; } const [o]: any = await connection.query("INSERT INTO orders(userId,status,totalPrice,fulfillmentStatus)VALUES(?,'delivered',1,'delivered')", [user]); const [i]: any = await connection.query("INSERT INTO orderItems(orderId,productId,quantity,unitPrice)VALUES(?,?,1,1)", [o.insertId, product]); const [r]: any = await connection.query("INSERT INTO stockReservations(orderId,userId,productId,orderItemId,quantity,status,expiresAt)VALUES(?,?,?,?,1,'consumed',DATE_ADD(NOW(),INTERVAL 1 DAY))", [o.insertId, user, product, i.insertId]); await connection.query("INSERT INTO payments(orderId,billingType,amount,externalReference,status,confirmedAt)VALUES(?,'PIX',1,?,'confirmed',NOW())", [o.insertId, crypto.randomUUID()]); return { user, product, reservation: r.insertId }; }
async function token(user: number, product: number, state: "valid" | "expired" | "claimed" = "valid") { const value = randomBytes(32).toString("base64url"); await connection.query("INSERT INTO productReviewUploads(token,userId,productId,imageUrl,expiresAt,claimedAt)VALUES(?,?,?,?,DATE_ADD(NOW(),INTERVAL ? MINUTE),?)", [value, user, product, `https://example.invalid/${value}.webp`, state === "expired" ? -1 : 15, state === "claimed" ? new Date() : null]); return value; }

describe.runIf(/test/i.test(url))("review upload token claim", () => { beforeAll(async () => { connection = await mysql.createConnection(url); const [r]: any = await connection.query("SELECT DATABASE() name"); if (!/test/i.test(r[0].name)) throw Error("test database required"); }); beforeEach(clean); afterAll(() => connection?.end());
  it("claims a valid token into a pending review and keeps tokenless reviews empty", async () => { const s = await purchase(); const image = await token(s.user, s.product); await caller(s.user).products.reviewCreate({ stockReservationId: s.reservation, rating: 5, reviewImageToken: image }); const [reviews]: any = await connection.query("SELECT imageUrl,imageStatus FROM productReviews"); expect(reviews[0]).toMatchObject({ imageStatus: "pending" }); expect(reviews[0].imageUrl).toContain(image); const [uploads]: any = await connection.query("SELECT claimedAt FROM productReviewUploads WHERE token=?", [image]); expect(uploads[0].claimedAt).not.toBeNull(); });
  it("rejects expired, claimed, foreign, wrong-product and unknown tokens without a review", async () => { const s = await purchase(); const other = await purchase(); const cases = [await token(s.user, s.product, "expired"), await token(s.user, s.product, "claimed"), await token(other.user, s.product), await token(s.user, other.product), randomBytes(32).toString("base64url")]; for (const value of cases) await expect(caller(s.user).products.reviewCreate({ stockReservationId: s.reservation, rating: 5, reviewImageToken: value })).rejects.toThrow("REVIEW_IMAGE_TOKEN_INVALID"); const [rows]: any = await connection.query("SELECT COUNT(*) total FROM productReviews"); expect(rows[0].total).toBe(0); });
  it("allows one concurrent claim for one token", async () => { const a = await purchase(); const b = await purchase(a.user, a.product); const image = await token(a.user, a.product); const results = await Promise.allSettled([caller(a.user).products.reviewCreate({ stockReservationId: a.reservation, rating: 5, reviewImageToken: image }), caller(a.user).products.reviewCreate({ stockReservationId: b.reservation, rating: 4, reviewImageToken: image })]); expect(results.filter(result => result.status === "fulfilled")).toHaveLength(1); expect(String((results.find(result => result.status === "rejected") as PromiseRejectedResult).reason)).toContain("REVIEW_IMAGE_TOKEN_INVALID"); const [reviews]: any = await connection.query("SELECT COUNT(*) total FROM productReviews"); const [uploads]: any = await connection.query("SELECT claimedAt FROM productReviewUploads WHERE token=?", [image]); expect(reviews[0].total).toBe(1); expect(uploads[0].claimedAt).not.toBeNull(); });
  it("rolls back a losing token claim when review uniqueness rejects the insert", async () => { const s = await purchase(); const first = await token(s.user, s.product); const second = await token(s.user, s.product); const results = await Promise.allSettled([caller(s.user).products.reviewCreate({ stockReservationId: s.reservation, rating: 5, reviewImageToken: first }), caller(s.user).products.reviewCreate({ stockReservationId: s.reservation, rating: 4, reviewImageToken: second })]); expect(results.filter(result => result.status === "fulfilled")).toHaveLength(1); const [reviews]: any = await connection.query("SELECT COUNT(*) total FROM productReviews"); const [uploads]: any = await connection.query("SELECT token,claimedAt FROM productReviewUploads ORDER BY token"); expect(reviews[0].total).toBe(1); expect(uploads.filter((row: any) => row.claimedAt !== null)).toHaveLength(1); });
});
