import mysql, { type Connection } from "mysql2/promise";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";
const url=process.env.TEST_DATABASE_URL||""; const enabled=/test/i.test(url); let c:Connection;
async function cleanDatabase(){for(const t of ["productReviews","payments","stockReservations","orderItems","orders","products","users"])await c.query(`DELETE FROM \`${t}\``)}
function caller(id:number){const now=new Date();return appRouter.createCaller({user:{id,openId:`review-${id}`,name:"Review",email:"r@test",cpf:null,phone:null,asaasCustomerId:null,loginMethod:"local",role:"user",isVip:0,isBlocked:0,sessionVersion:1,createdAt:now,updatedAt:now,lastSignedIn:now},req:{protocol:"http",headers:{}} as TrpcContext["req"],res:{} as TrpcContext["res"]})}
async function seedEligiblePurchase(payment:{status?:string;confirmed?:boolean;received?:boolean;absent?:boolean}={}){const [u]:any=await c.query("INSERT INTO users(openId) VALUES(?)",[crypto.randomUUID()]);const [p]:any=await c.query("INSERT INTO products(name,category,price,stock) VALUES('p','c',100,1)");const [o]:any=await c.query("INSERT INTO orders(userId,status,totalPrice,fulfillmentStatus) VALUES(?, 'delivered',100,'delivered')",[u.insertId]);const [i]:any=await c.query("INSERT INTO orderItems(orderId,productId,quantity,unitPrice) VALUES(?,?,1,100)",[o.insertId,p.insertId]);const [r]:any=await c.query("INSERT INTO stockReservations(orderId,userId,productId,orderItemId,quantity,status,expiresAt) VALUES(?,?,?,?,1,'consumed',DATE_ADD(NOW(),INTERVAL 1 DAY))",[o.insertId,u.insertId,p.insertId,i.insertId]);if(!payment.absent)await c.query("INSERT INTO payments(orderId,billingType,amount,externalReference,status,confirmedAt,receivedAt) VALUES(?, 'PIX',100,?,?,?,?)",[o.insertId,crypto.randomUUID(),payment.status??"confirmed",payment.confirmed===false?null:new Date(),payment.received?new Date():null]);return{userId:u.insertId,productId:p.insertId,orderId:o.insertId,reservationId:r.insertId}}
describe.runIf(enabled)("verified reviews 3B MySQL smoke",()=>{beforeAll(async()=>{process.env.DATABASE_URL=url;c=await mysql.createConnection(url);const [r]:any=await c.query("SELECT DATABASE() name");if(!/test/i.test(r[0].name))throw Error("test database required")});beforeEach(cleanDatabase);afterAll(()=>c?.end());it("eligibility valid",async()=>{const s=await seedEligiblePurchase();expect((await caller(s.userId).products.reviewEligibility()).at(0)).toMatchObject({eligible:true,stockReservationId:s.reservationId})});it("creates verified review",async()=>{const s=await seedEligiblePurchase();await caller(s.userId).products.reviewCreate({stockReservationId:s.reservationId,rating:5,comment:"ok",sizePerception:"true_to_size"});const [r]:any=await c.query("SELECT * FROM productReviews WHERE stockReservationId=?",[s.reservationId]);expect(r[0]).toMatchObject({verifiedPurchase:1,userId:s.userId,productId:s.productId,orderId:s.orderId,imageUrl:null,imageStatus:"none",moderationStatus:"published"})});it("pending payment denied",async()=>{const s=await seedEligiblePurchase({status:"pending",confirmed:false});expect(await caller(s.userId).products.reviewEligibility()).toEqual([]);await expect(caller(s.userId).products.reviewCreate({stockReservationId:s.reservationId,rating:5})).rejects.toThrow("REVIEW_NOT_ELIGIBLE")});it("legacy upsert blocked",async()=>{const s=await seedEligiblePurchase();await expect(caller(s.userId).products.reviewUpsert({productId:s.productId,rating:5})).rejects.toThrow("REVIEW_UPSERT_DISABLED_USE_REVIEW_CREATE");const [r]:any=await c.query("SELECT count(*) n FROM productReviews");expect(r[0].n).toBe(0)});for(const [name,payment,ok] of [["confirmed timestamp",{status:"confirmed",confirmed:true},true],["confirmed no timestamp",{status:"confirmed",confirmed:false},false],["received receivedAt",{status:"received",confirmed:false,received:true},true],["received confirmedAt",{status:"received",confirmed:true},true],["received no timestamp",{status:"received",confirmed:false},false],["failed",{status:"failed",confirmed:false},false],["overdue",{status:"overdue",confirmed:false},false],["cancelled",{status:"cancelled",confirmed:false},false],["partially refunded",{status:"partially_refunded",confirmed:false},false],["refunded",{status:"refunded",confirmed:false},false],["chargeback",{status:"chargeback",confirmed:false},false],["no payment",{absent:true},false]] as const)it(`finance ${name}`,async()=>{const s=await seedEligiblePurchase(payment);expect((await caller(s.userId).products.reviewEligibility()).length>0).toBe(ok);if(!ok&&["confirmed no timestamp","failed","refunded","no payment"].includes(name)){await expect(caller(s.userId).products.reviewCreate({stockReservationId:s.reservationId,rating:5})).rejects.toThrow("REVIEW_NOT_ELIGIBLE");const [r]:any=await c.query("SELECT count(*) n FROM productReviews");expect(r[0].n).toBe(0)}})});
