export const emailSubjects = {
  comingSoonConfirmation: "Seu acesso antecipado à L4CKOS foi confirmado",
  contactConfirmation: "Recebemos sua mensagem",
  newContactInternal: ({ subject }) => `Novo contato do site: ${subject || "L4CKOS"}`,
  welcomeAccount: "Sua conta L4CKOS está pronta",
  passwordReset: "Redefina sua senha da L4CKOS",
  paymentNotFinished: ({ orderNumber }) => `O pedido #${orderNumber} ainda pode ser concluído`,
  orderCreated: ({ orderNumber }) => `Recebemos o pedido #${orderNumber}`,
  paymentPending: ({ orderNumber }) => `Pagamento pendente do pedido #${orderNumber}`,
  paymentApproved: ({ orderNumber }) => `Pagamento aprovado para o pedido #${orderNumber}`,
  paymentFailed: ({ orderNumber }) => `Pagamento não aprovado para o pedido #${orderNumber}`,
  internalNewSaleAlert: ({ orderNumber }) => `Nova venda confirmada: pedido #${orderNumber}`,
  internalLowStockAlert: ({ totalProducts }) => `Estoque baixo: ${totalProducts || 0} item(ns) exigem atenção`,
  internalPaymentFailedAlert: ({ orderNumber }) => `Falha de pagamento no pedido #${orderNumber}`,
  orderPreparing: ({ orderNumber }) => `Pedido #${orderNumber} em preparação`,
  orderShipped: ({ orderNumber }) => `Pedido #${orderNumber} enviado`,
  orderDelivered: ({ orderNumber }) => `Pedido #${orderNumber} entregue`,
  reviewRequest: ({ orderNumber }) => `Como foi sua experiência com o pedido #${orderNumber}?`,
  launchAnnouncement: "A L4CKOS está no ar",
  newDropAnnouncement: "Novo drop L4CKOS disponível",
  newProductsAnnouncement: "Novidades no catálogo da L4CKOS",
  promotionEmail: "Uma condição especial está ativa na L4CKOS",
  abandonedCartReminder1: "Sua seleção continua no carrinho",
  abandonedCartReminder2: "Os itens do seu carrinho ainda estão disponíveis",
  abandonedCartReminder3: "Último lembrete sobre sua seleção",
  crossSellEmail: "Uma seleção que combina com sua última compra",
  loyaltyCouponEmail: "Seu benefício de fidelidade está disponível",
};
