import { useState, type ChangeEvent, type FormEvent } from "react";
import { Star } from "lucide-react";
import { trpc } from "../../lib/trpc";
import { apiUrl } from "../../const";
import { csrfFetch } from "../../lib/csrf";
import "./reviews.css";
type Size = "" | "small" | "true_to_size" | "large";
export function ReviewPurchaseArea({ productId }: { productId: number }) {
 const utils=trpc.useUtils(), eligibility=trpc.products.reviewEligibility.useQuery({productId},{refetchOnWindowFocus:false}), create=trpc.products.reviewCreate.useMutation();
 const [selected,setSelected]=useState<number|null>(null),[rating,setRating]=useState(0),[comment,setComment]=useState(""),[size,setSize]=useState<Size>(""),[image,setImage]=useState<File|null>(null),[message,setMessage]=useState("");
 const rows=(eligibility.data??[]).filter(row=>row.eligible); const pending=create.isPending;
 async function submit(event:FormEvent){event.preventDefault();if(!selected||rating<1)return setMessage("Selecione uma nota de 1 a 5 estrelas.");try { let reviewImageToken: string|undefined; if(image){const form=new FormData();form.append("productId",String(productId));form.append("file",image);const res=await csrfFetch(apiUrl("/api/review-images"),{method:"POST",body:form});const body=await res.json().catch(()=>null);if(!res.ok||!body?.token)throw new Error(body?.message||"Não foi possível enviar a foto.");reviewImageToken=String(body.token);} await create.mutateAsync({stockReservationId:selected,rating,comment:comment.trim()||undefined,sizePerception:size||undefined,reviewImageToken});await Promise.all([eligibility.refetch(),utils.products.reviews.invalidate(productId)]);setSelected(null);setRating(0);setComment("");setSize("");setImage(null);setMessage(reviewImageToken?"Avaliação enviada. A foto passará por moderação.":"Avaliação publicada.");}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível enviar sua avaliação.");}}
 function imageChange(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]||null;if(file&&(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>3*1024*1024)){e.target.value="";setImage(null);setMessage("Use JPG, PNG ou WEBP de até 3 MB.");return;}setImage(file);}
 if(eligibility.isLoading)return <section className="l4-review-purchase-area"><p>Verificando compras elegíveis...</p></section>; if(!rows.length)return null;
 return <section className="l4-review-purchase-area"><h2>Avalie sua compra</h2>{!selected?<div className="l4-review-eligible-list">{rows.map(row=><button key={row.stockReservationId} type="button" onClick={()=>setSelected(row.stockReservationId)}>Avaliar compra #{row.orderId}</button>)}</div>:<form className="l4-review-form" onSubmit={submit}><div className="l4-review-rating-input">{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>setRating(n)} aria-label={`${n} estrelas`}><Star fill={n<=rating?"currentColor":"none"}/></button>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} placeholder="Conte sua experiência (opcional)"/><div className="l4-review-size-options">{(["small","true_to_size","large"] as const).map(value=><label key={value}><input type="radio" checked={size===value} onChange={()=>setSize(value)}/>{value==="small"?"Pequeno":value==="large"?"Grande":"Ideal"}</label>)}</div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={imageChange}/><button className="l4-review-submit" disabled={pending}>{pending?"Enviando...":"Publicar avaliação"}</button></form>}{message?<p className="l4-review-feedback">{message}</p>:null}</section>;
}
